import { renderHook } from '@testing-library/react-hooks';
import * as hooks from './useFetchNodes';

const baseUrl = '/base';

const dataMock: Promise<any> = Promise.resolve([
  {
    id: '972c5e17-a341-4aa7-9598-31fd0aef8e26',
    name: 'ip-10-200-169-17.ec2.internal',
    services: [],
    os: 'linux',
    osName: 'Amazon Linux',
    osVersion: '2',
    kernelName: 'Linux',
    kernelVersion: '5.4.196-108.356.amzn2.x86_64',
    architecture: 'x86_64',
    cpus: 32,
    cpuFrequency: '3.597 GHz',
    memory: '123 GiB',
    diskSpace: '1.1 TiB',
    virtualization: 'kvm',
    container: 'docker',
    version: 'unknown',
    machineGUID: '25a97892-f155-11ec-90b2-0a4315960f87',
    hostLabels: {
      _aclk_available: 'true',
      _aclk_ng_new_cloud_protocol: 'true',
      _aclk_proxy: 'none',
      _architecture: 'x86_64',
      _cloud_instance_region: 'us-east-1',
      _cloud_instance_type: 'm6a.8xlarge',
      _cloud_provider_type: 'AWS',
      _container: 'docker',
      _container_detection: 'dockerenv',
      _install_type: 'oci',
      _is_k8s_node: 'true',
      _is_parent: 'false',
      _kernel_version: '5.4.196-108.356.amzn2.x86_64',
      _mqtt_version: '5',
      _os_name: 'Amazon Linux',
      _os_version: '2',
      _prebuilt_arch: 'x86_64',
      _streams_to: 'netdata:19999',
      _system_cores: '32',
      _system_cpu_freq: '3597000000',
      _system_disk_space: '1245540515840',
      _system_ram_total: '132329742336',
      _virt_detection: 'lscpu',
      _virtualization: 'kvm',
      app: 'netdata',
      cloud_provider: 'aws',
      'controller-revision-hash': 'cbc558d7',
      environment: 'production',
      k8s_cluster_id: '7a138c6a-daf3-40f7-9eb4-bda58682842c',
      'pod-template-generation': '24',
      release: 'netdata',
      role: 'child',
    },
    mlInfo: {
      mlCapable: true,
      mlEnabled: true,
    },
    capabilities: [
      {
        name: 'proto',
        version: 1,
        enabled: true,
      },
      {
        name: 'ml',
        version: 1,
        enabled: true,
      },
      {
        name: 'mc',
        version: 1,
        enabled: true,
      },
      {
        name: 'ctx',
        version: 1,
        enabled: true,
      },
    ],
    alarmCounters: {
      warning: 4,
      critical: 0,
    },
    isDeleted: false,
    state: 'stale',
  },
  {
    id: 'ca1c7695-88e4-4124-b54f-804b297e6e9d',
    name: 'ip-10-200-132-249.ec2.internal',
    services: [],
    os: 'linux',
    osName: 'Amazon Linux',
    osVersion: '2',
    kernelName: 'Linux',
    kernelVersion: '5.4.196-108.356.amzn2.x86_64',
    architecture: 'x86_64',
    cpus: 32,
    cpuFrequency: '3.598 GHz',
    memory: '123 GiB',
    diskSpace: '932 GiB',
    virtualization: 'kvm',
    container: 'docker',
    version: 'unknown',
    machineGUID: '41c8ae42-ed60-11ec-a450-02b70ba16781',
    hostLabels: {
      _aclk_available: 'true',
      _aclk_ng_new_cloud_protocol: 'true',
      _aclk_proxy: 'none',
      _architecture: 'x86_64',
      _cloud_instance_region: 'us-east-1',
      _cloud_instance_type: 'm6a.8xlarge',
      _cloud_provider_type: 'AWS',
      _container: 'docker',
      _container_detection: 'dockerenv',
      _install_type: 'oci',
      _is_k8s_node: 'true',
      _is_parent: 'false',
      _kernel_version: '5.4.196-108.356.amzn2.x86_64',
      _mqtt_version: '5',
      _os_name: 'Amazon Linux',
      _os_version: '2',
      _prebuilt_arch: 'x86_64',
      _streams_to: 'netdata:19999',
      _system_cores: '32',
      _system_cpu_freq: '3598000000',
      _system_disk_space: '1000727379968',
      _system_ram_total: '132329742336',
      _virt_detection: 'lscpu',
      _virtualization: 'kvm',
      app: 'netdata',
      cloud_provider: 'aws',
      'controller-revision-hash': 'cbc558d7',
      environment: 'production',
      k8s_cluster_id: '7a138c6a-daf3-40f7-9eb4-bda58682842c',
      'pod-template-generation': '24',
      release: 'netdata',
      role: 'child',
    },
    mlInfo: {
      mlCapable: true,
      mlEnabled: true,
    },
    capabilities: [
      {
        name: 'proto',
        version: 1,
        enabled: true,
      },
      {
        name: 'ml',
        version: 1,
        enabled: true,
      },
      {
        name: 'mc',
        version: 1,
        enabled: true,
      },
      {
        name: 'ctx',
        version: 1,
        enabled: true,
      },
    ],
    alarmCounters: {
      warning: 0,
      critical: 0,
    },
    isDeleted: false,
    state: 'stale',
  },
  {
    id: 'f7bb0f66-f44c-4d0e-ade4-ef0e57a47bdb',
    name: 'ip-10-200-146-224.ec2.internal',
    services: [],
    os: 'linux',
    osName: 'Amazon Linux',
    osVersion: '2',
    kernelName: 'Linux',
    kernelVersion: '5.4.204-113.362.amzn2.x86_64',
    architecture: 'x86_64',
    cpus: 8,
    cpuFrequency: '3.576 GHz',
    memory: '31 GiB',
    diskSpace: '100 GiB',
    virtualization: 'kvm',
    container: 'docker',
    version: 'unknown',
    machineGUID: '2bd7b99c-12fa-11ed-9194-126b3a509b9b',
    hostLabels: null,
    mlInfo: {
      mlCapable: true,
      mlEnabled: true,
    },
    capabilities: [
      {
        name: 'mc',
        version: 1,
        enabled: true,
      },
      {
        name: 'ctx',
        version: 1,
        enabled: true,
      },
      {
        name: 'proto',
        version: 1,
        enabled: true,
      },
      {
        name: 'ml',
        version: 1,
        enabled: true,
      },
    ],
    alarmCounters: {
      warning: 0,
      critical: 0,
    },
    isDeleted: false,
    state: 'stale',
  },
]);

describe('useFetchNodes', () => {
  it('return correct data', async () => {
    jest.spyOn(hooks, 'getNodes').mockImplementation(() => dataMock);

    const { result, waitFor } = renderHook(() => hooks.useFetchNodes(baseUrl));

    await result.current.fetchNodes('spaceId', 'roomId');

    await waitFor(() => result.current.nodes.length > 0);

    expect(result.current.nodes).toBeDefined();
    expect(result.current.nodes).toEqual([
      {
        id: '972c5e17-a341-4aa7-9598-31fd0aef8e26',
        name: 'ip-10-200-169-17.ec2.internal',
        services: [],
        os: 'linux',
        osName: 'Amazon Linux',
        osVersion: '2',
        kernelName: 'Linux',
        kernelVersion: '5.4.196-108.356.amzn2.x86_64',
        architecture: 'x86_64',
        cpus: 32,
        cpuFrequency: '3.597 GHz',
        memory: '123 GiB',
        diskSpace: '1.1 TiB',
        virtualization: 'kvm',
        container: 'docker',
        version: 'unknown',
        machineGUID: '25a97892-f155-11ec-90b2-0a4315960f87',
        hostLabels: {
          _aclk_available: 'true',
          _aclk_ng_new_cloud_protocol: 'true',
          _aclk_proxy: 'none',
          _architecture: 'x86_64',
          _cloud_instance_region: 'us-east-1',
          _cloud_instance_type: 'm6a.8xlarge',
          _cloud_provider_type: 'AWS',
          _container: 'docker',
          _container_detection: 'dockerenv',
          _install_type: 'oci',
          _is_k8s_node: 'true',
          _is_parent: 'false',
          _kernel_version: '5.4.196-108.356.amzn2.x86_64',
          _mqtt_version: '5',
          _os_name: 'Amazon Linux',
          _os_version: '2',
          _prebuilt_arch: 'x86_64',
          _streams_to: 'netdata:19999',
          _system_cores: '32',
          _system_cpu_freq: '3597000000',
          _system_disk_space: '1245540515840',
          _system_ram_total: '132329742336',
          _virt_detection: 'lscpu',
          _virtualization: 'kvm',
          app: 'netdata',
          cloud_provider: 'aws',
          'controller-revision-hash': 'cbc558d7',
          environment: 'production',
          k8s_cluster_id: '7a138c6a-daf3-40f7-9eb4-bda58682842c',
          'pod-template-generation': '24',
          release: 'netdata',
          role: 'child',
        },
        mlInfo: {
          mlCapable: true,
          mlEnabled: true,
        },
        capabilities: [
          {
            name: 'proto',
            version: 1,
            enabled: true,
          },
          {
            name: 'ml',
            version: 1,
            enabled: true,
          },
          {
            name: 'mc',
            version: 1,
            enabled: true,
          },
          {
            name: 'ctx',
            version: 1,
            enabled: true,
          },
        ],
        alarmCounters: {
          warning: 4,
          critical: 0,
        },
        isDeleted: false,
        state: 'stale',
      },
      {
        id: 'ca1c7695-88e4-4124-b54f-804b297e6e9d',
        name: 'ip-10-200-132-249.ec2.internal',
        services: [],
        os: 'linux',
        osName: 'Amazon Linux',
        osVersion: '2',
        kernelName: 'Linux',
        kernelVersion: '5.4.196-108.356.amzn2.x86_64',
        architecture: 'x86_64',
        cpus: 32,
        cpuFrequency: '3.598 GHz',
        memory: '123 GiB',
        diskSpace: '932 GiB',
        virtualization: 'kvm',
        container: 'docker',
        version: 'unknown',
        machineGUID: '41c8ae42-ed60-11ec-a450-02b70ba16781',
        hostLabels: {
          _aclk_available: 'true',
          _aclk_ng_new_cloud_protocol: 'true',
          _aclk_proxy: 'none',
          _architecture: 'x86_64',
          _cloud_instance_region: 'us-east-1',
          _cloud_instance_type: 'm6a.8xlarge',
          _cloud_provider_type: 'AWS',
          _container: 'docker',
          _container_detection: 'dockerenv',
          _install_type: 'oci',
          _is_k8s_node: 'true',
          _is_parent: 'false',
          _kernel_version: '5.4.196-108.356.amzn2.x86_64',
          _mqtt_version: '5',
          _os_name: 'Amazon Linux',
          _os_version: '2',
          _prebuilt_arch: 'x86_64',
          _streams_to: 'netdata:19999',
          _system_cores: '32',
          _system_cpu_freq: '3598000000',
          _system_disk_space: '1000727379968',
          _system_ram_total: '132329742336',
          _virt_detection: 'lscpu',
          _virtualization: 'kvm',
          app: 'netdata',
          cloud_provider: 'aws',
          'controller-revision-hash': 'cbc558d7',
          environment: 'production',
          k8s_cluster_id: '7a138c6a-daf3-40f7-9eb4-bda58682842c',
          'pod-template-generation': '24',
          release: 'netdata',
          role: 'child',
        },
        mlInfo: {
          mlCapable: true,
          mlEnabled: true,
        },
        capabilities: [
          {
            name: 'proto',
            version: 1,
            enabled: true,
          },
          {
            name: 'ml',
            version: 1,
            enabled: true,
          },
          {
            name: 'mc',
            version: 1,
            enabled: true,
          },
          {
            name: 'ctx',
            version: 1,
            enabled: true,
          },
        ],
        alarmCounters: {
          warning: 0,
          critical: 0,
        },
        isDeleted: false,
        state: 'stale',
      },
      {
        id: 'f7bb0f66-f44c-4d0e-ade4-ef0e57a47bdb',
        name: 'ip-10-200-146-224.ec2.internal',
        services: [],
        os: 'linux',
        osName: 'Amazon Linux',
        osVersion: '2',
        kernelName: 'Linux',
        kernelVersion: '5.4.204-113.362.amzn2.x86_64',
        architecture: 'x86_64',
        cpus: 8,
        cpuFrequency: '3.576 GHz',
        memory: '31 GiB',
        diskSpace: '100 GiB',
        virtualization: 'kvm',
        container: 'docker',
        version: 'unknown',
        machineGUID: '2bd7b99c-12fa-11ed-9194-126b3a509b9b',
        hostLabels: null,
        mlInfo: {
          mlCapable: true,
          mlEnabled: true,
        },
        capabilities: [
          {
            name: 'mc',
            version: 1,
            enabled: true,
          },
          {
            name: 'ctx',
            version: 1,
            enabled: true,
          },
          {
            name: 'proto',
            version: 1,
            enabled: true,
          },
          {
            name: 'ml',
            version: 1,
            enabled: true,
          },
        ],
        alarmCounters: {
          warning: 0,
          critical: 0,
        },
        isDeleted: false,
        state: 'stale',
      },
    ]);
  });
});
